name: build and deploy
on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
  deploy-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    needs: [test, build]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yml
          VAR: image=${{ needs.build.outputs.image }}